# Generated by Django 3.2 on 2025-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس شرکت'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس شرکت'),
        ),
    ]
