# Generated by Django 3.2 on 2024-04-18 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListModel', to='billboard.billboardmodel', verbose_name='بیلبورد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListModel', to=settings.AUTH_USER_MODEL, verbose_name='لیست کاربر')),
            ],
        ),
    ]
