# Generated by Django 3.2 on 2026-05-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listsmodel',
            options={'verbose_name': 'آیتم لیست کاربر', 'verbose_name_plural': 'لیست کاربران'},
        ),
    ]
