# Generated by Django 3.2 on 2024-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'integer'), (1, 'string'), (2, 'float'), (3, 'boolean')], default=1)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
