# Generated by Django 3.2 on 2024-04-18 06:15

import billboard.mixin
import billboard.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی بیلبورد')),
            ],
            options={
                'verbose_name': 'ویژگی بیلبورد',
                'verbose_name_plural': 'ویژگی های بیلبورد',
            },
        ),
        migrations.CreateModel(
            name='BillboardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='آدرس صفحه')),
                ('desc', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیحات صفحه')),
                ('name', models.CharField(max_length=255, verbose_name='اسم دسته بندی')),
                ('billboard_visibility', models.BooleanField(default=True, verbose_name='نمایش بیلبورد ها در این دسته بندی؟')),
                ('priority', models.SmallIntegerField(blank=True, default=0, verbose_name='اولیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillboardCategory', to='billboard.billboardcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='آدرس صفحه')),
                ('desc', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیحات صفحه')),
                ('name', models.CharField(max_length=100, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='آدرس صفحه')),
                ('desc', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیحات صفحه')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CityModel', to='billboard.statemodel', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='BillboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='آدرس صفحه')),
                ('desc', models.TextField(blank=True, max_length=160, null=True, verbose_name='توضیحات صفحه')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیلبورد')),
                ('address', models.CharField(max_length=250, verbose_name='محل بیلبورد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات بیلبورد')),
                ('has_power', models.BooleanField(default=True, verbose_name='روشنایی')),
                ('billboard_length', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='طول بیلبورد')),
                ('billboard_width', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='عرض بیلبورد')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('reservation_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ اکران')),
                ('map_iframe', models.TextField(blank=True, null=True, verbose_name='نقشه')),
                ('billboard_pic', models.ImageField(blank=True, null=True, upload_to=billboard.utils.billboard_path, verbose_name='تصویر اصلی بیلبورد')),
                ('billboard_status', models.PositiveSmallIntegerField(choices=[(0, 'نمایش در سایت'), (1, 'پیش نویس'), (2, 'آرشیو'), (3, 'غیر قابل فروش')], default=0, verbose_name='وضعیت بیلبورد')),
                ('attribute', models.ManyToManyField(blank=True, to='billboard.BillboardAttributeModel', verbose_name='ویژگی های بیلبورد')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillboardModel', to='billboard.billboardcategory', verbose_name='دسته بندی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillboardModel', to='billboard.citymodel', verbose_name='شهر')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'بیلبورد',
                'verbose_name_plural': 'بیلبورد ها',
                'permissions': (('can_import_billboard', 'اجاره وارد کردن گروهی بیلبورد'),),
            },
            bases=(models.Model, billboard.mixin.ImageCompressMixin),
        ),
        migrations.CreateModel(
            name='BillboardImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to=billboard.utils.billboard_path, verbose_name='عکس')),
                ('billboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillboardImageModel', to='billboard.billboardmodel', verbose_name='تصویر بیلبورد')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillboardImageModel', to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
            ],
            options={
                'verbose_name': 'عکس بیلبورد',
                'verbose_name_plural': 'عکس های بیلبورد',
            },
            bases=(models.Model, billboard.mixin.ImageCompressMixin),
        ),
        migrations.CreateModel(
            name='BillboardFinalPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_price', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='قیمت افزوده')),
                ('final_price', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='قیمت نهایی')),
                ('billboard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillboardFinalPriceModel', to='billboard.billboardmodel')),
            ],
            options={
                'verbose_name': 'قیمت نهایی',
                'verbose_name_plural': 'قیمت های نهایی',
            },
        ),
    ]
