# Generated by Django 3.2 on 2025-05-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20240418_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
            ],
        ),
        migrations.AddField(
            model_name='billboardmodel',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billboards', to='billboard.companymodel', verbose_name='شرکت صاحب امتیاز'),
        ),
    ]
