# Generated by Django 3.2 on 2025-05-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('billboard', '0003_auto_20250515_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboardmodel',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billboards', to='account.companymodel', verbose_name='شرکت صاحب امتیاز'),
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
    ]
