# Generated by Django 3.2 on 2024-04-18 06:15

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billboard', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ قراداد')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContractModel', to='account.brandmodel', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قرارداد ها',
            },
        ),
        migrations.CreateModel(
            name='RentalListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع قراداد')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان قراداد')),
                ('months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد ماه های قراداد')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت هر ماه')),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RentalListModel', to='billboard.billboardmodel', verbose_name='بیلبورد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RentalListModel', to='reservation.contractmodel', verbose_name='قرداد')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزرو ها',
                'permissions': (('can_check_reservation', 'اجاره برسی رزرو ها'),),
            },
        ),
    ]
